# Generated by Django 3.2.8 on 2021-10-23 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(db_constraint=False, related_name='products', to='categories.Category')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=256, verbose_name='상품명')),
                ('price', models.BigIntegerField(default=0, null=True, verbose_name='상품 가격')),
                ('description', models.CharField(max_length=256, verbose_name='상품 상세')),
                ('is_active', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('is_published', models.BooleanField(default=False, verbose_name='전시 여부')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'deleted_at'], name='active_products'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_published', 'deleted_at'], name='publish_products'),
        ),
    ]
