@BASE_URL = http://127.0.0.1:8000
# @BASE_URL=http://sjahn.pythonanywhere.com


###
# auth.register
POST {{ BASE_URL }}/api/auth/register
Content-Type: application/json

{
    "email": "abc123@abc.com",
    "name": "tester",
    "password": "rewq1234"
}


###
# @name login
POST {{ BASE_URL }}/api/auth/login
Content-Type: application/json

{
    "email": "sjahn@ktown4u.com",
    "password": "rewq1234"
}

###
@authorized = {{ login.response.body.token }}


###
# auth.me
GET {{ BASE_URL }}/api/auth/me
Content-Type: application/json
Authorization: Bearer {{ authorized }}


### posts.lists
GET {{ BASE_URL }}/api/posts
Content-Type: application/json


### posts.create
POST {{ BASE_URL }}/api/posts
Content-Type: application/json
Authorization: Bearer {{ authorized }}

{
    "title": "hello world",
    "body": "my father goes to the market with donkey ..."
}


### posts.show
GET {{ BASE_URL }}/api/posts/10
Content-Type: application/json
Authorization: Bearer {{ authorized }}


### posts.update
PUT {{ BASE_URL }}/api/posts/1
Content-Type: application/json
Authorization: Bearer {{ authorized }}

{
    "title": "hohohohoho rorororo"
}


### posts.destroy
DELETE {{ BASE_URL }}/api/posts/1
Content-Type: application/json
Authorization: Bearer {{ authorized }}


### posts.comments.list
GET {{ BASE_URL }}/api/posts/1/comments
Content-Type: application/json
Authorization: Bearer {{ authorized }}


### posts.comments.create
POST {{ BASE_URL }}/api/posts/10/comments
Content-Type: application/json
Authorization: Bearer {{ authorized }}

{
    "body": "Me Too!!"
}


### posts.comments.update
PUT {{ BASE_URL }}/api/posts/1/comments/10
Content-Type: application/json
Authorization: Bearer {{ authorized }}

{
    "body": "Nice To Meet You!!!"
}


### posts.comments.delete
DELETE {{ BASE_URL }}/api/posts/1/comments/10
Content-Type: application/json
Authorization: Bearer {{ authorized }}


### banner_categories
GET {{ BASE_URL }}/api/banner_categories
Content-Type: application/json
Authorization: Bearer {{ authorized }}


### pages.lists
GET {{ BASE_URL }}/api/pages
Content-Type: application/json


### pages.create
POST {{ BASE_URL }}/api/pages
Content-Type: application/json

{
    "name": "회원 등록 페이지",
    "path": "/menus"
}


### menus.lists
GET {{ BASE_URL }}/api/menus
Content-Type: application/json


### menus.lists
GET {{ BASE_URL }}/api/menus/tree
Content-Type: application/json


### menus.create
POST {{ BASE_URL }}/api/menus
Content-Type: application/json

{
    "name": "메뉴 관리",
    "descr": "메뉴 관리 페이지입니다.",
    "parent_id": null,
    "order": 2,
    "is_published": true,
    "page_id": 3
}


### menus.create
POST {{ BASE_URL }}/api/menus
Content-Type: application/json

{
    "name": "회원 목록",
    "descr": "회원 목록 페이지입니다.",
    "parent_id": 1,
    "order": 1,
    "is_published": true,
    "page_id": 1
}


### base_items.list
GET {{ BASE_URL }}/api/base_items
Content-Type: application/json


### base_items.show
GET {{ BASE_URL }}/api/base_items/34
Content-Type: application/json


### base_items.create general
POST {{ BASE_URL }}/api/base_items
Content-Type: application/json

{
    "name": "정관장 홍삼 30일",
    "kind": "general",
    "is_active": true
}

### base_items.create option
POST {{ BASE_URL }}/api/base_items
Content-Type: application/json

{
    "name": "글로 네오",
    "kind": "option",
    "is_active": true,
    "options": [
        {
            "name": "type",
            "values": [
                {
                    "name": "퍼플 부스트"
                },
                {
                    "name": "프레시"
                }
            ]
        }
    ]
}


### base_items.create option
POST {{ BASE_URL }}/api/base_items
Content-Type: application/json

{
    "name": "무지 티셔츠",
    "kind": "option",
    "is_active": true,
    "options": [
        {
            "name": "color",
            "values": [
                {
                    "name": "White"
                },
                {
                    "name": "Black"
                }
            ]
        },
        {
            "name": "size",
            "values": [
                {
                    "name": "M"
                },
                {
                    "name": "L"
                }
            ]
        }
    ]
}



### base_items.create option
POST {{ BASE_URL }}/api/base_items
Content-Type: application/json

{
    "name": "무지 티셔츠",
    "kind": "option",
    "is_active": true,
    "options": [
        {
            "name": "color",
            "values": [
                {
                    "name": "White"
                },
                {
                    "name": "Black"
                }
            ]
        },
        {
            "name": "size",
            "values": [
                {
                    "name": "M"
                },
                {
                    "name": "L"
                }
            ]
        },
        {
            "name": "gender",
            "values": [
                {
                    "name": "M"
                },
                {
                    "name": "F"
                }
            ]
        }
    ]
}
