# Generated by Django 3.2.3 on 2021-06-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['deleted_at', 'commentable_id', 'commentable_type'], name='commentable'),
        ),
    ]
