# Generated by Django 3.2.3 on 2021-06-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='menu',
        ),
    ]
