# Generated by Django 3.2.3 on 2021-06-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='childrens', to='routes.route')),
                ('path', models.CharField(max_length=75, verbose_name='path')),
                ('name', models.CharField(max_length=75, verbose_name='name')),
                ('is_dynamic_component', models.BooleanField(default=False, verbose_name='가변 컴포넌트 여부')),
                ('component', models.CharField(max_length=125, verbose_name='components')),
                ('meta', models.JSONField(blank=True, default=None, null=True, verbose_name='route.meta')),
                ('depth', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['id', 'depth', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['deleted_at', 'is_published'], name='routes_deleted_707062_idx'),
        ),
    ]
