# Generated by Django 3.2.8 on 2021-10-23 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),                
                ('name', models.CharField(max_length=256, verbose_name='쿠폰명')),
                ('categories', models.ManyToManyField(db_constraint=False, related_name='coupons', to='categories.Category')),
                ('products', models.ManyToManyField(db_constraint=False, related_name='coupons', to='products.Product')),
                ('is_fixed_discount', models.BooleanField(default=False, verbose_name='고정할인 여부')),
                ('min_order_price', models.BigIntegerField(default=0, null=True, verbose_name='최소 주문 금액')),
                ('max_discount', models.BigIntegerField(default=0, null=True, verbose_name='최대 할인 금액')),
                ('expired_at', models.DateTimeField(null=True, verbose_name='만료일')),
                ('is_all_category', models.BooleanField(default=True, verbose_name='전체 카테고리 적용 여부')),
                ('is_all_product', models.BooleanField(default=True, verbose_name='전체 상품 적용 여부')),
                ('is_active', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'deleted_at'], name='active_coupons'),
        ),
    ]
