# Generated by Django 3.2.8 on 2021-10-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='products',
        ),
    ]
