# Generated by Django 3.2.8 on 2021-10-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20211023_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.JSONField(default=None, verbose_name='카테고리 아이디 list'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.JSONField(default=None, verbose_name='상품 아이디 list'),
        ),
    ]
