# Generated by Django 3.2.8 on 2021-10-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20211023_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.BigIntegerField(default=0, null=True, verbose_name='할인액'),
        ),
    ]
