# Generated by Django 3.2.3 on 2021-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='kind',
            field=models.CharField(default='general', max_length=24, verbose_name='구분'),
        ),
    ]
