# Generated by Django 3.2.3 on 2021-07-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_baseitem_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseitem',
            name='barcode',
        ),
    ]
