# Generated by Django 3.2.3 on 2021-06-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='childs', to='menus.menu')),
                ('name', models.CharField(max_length=75, verbose_name='name')),
                ('descr', models.CharField(max_length=75, verbose_name='메뉴 설명')),
                ('depth', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),

            ],
            options={
                'db_table': 'menus',
                'ordering': ['id', 'depth', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['deleted_at', 'is_published'], name='menus_deleted_c9e9ca_idx'),
        ),
    ]
