# Generated by Django 3.2.3 on 2021-07-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['depth', 'order', 'id']},
        ),
    ]
